* <<<PCP1111>>> ETHICAL PRACTICES
:properties:
:author: R.Kanchana, J Suresh
:date: 13 July 2018
:end:

#+startup: showall

{{{credits}}}
|L|T|P|C|
|0|0|2|1|

** Course Objectives
- To create an awareness on Engineering Ethics and Human Values.
- To understand social responsibility of an engineer.
- To appreciate ethical dilemma while discharging duties in
  professional life.

** Topics
1. Engineering Ethics (8 hours)\\
   Responsibility in Engineering, Analysing interior and exterior
   intensions, Moral judgements and responsibility

2. Human Values (4 hours)\\
   Morals, Values and Ethics – Integrity – Work Ethic – Honesty –
   Courage – Empathy – Self-Confidence – Character

3. Social and Value Dimensions in Technology (6 hours)\\
   Privacy and social policy, ethical issues in design, Approaches to
   risk, case studies

4. Engineers in Organizations (6 hours)\\
   Organizational culture, Clean environment, Fairness: person to
   person and social

5. Best Practices (6 hours)\\
   Moral behaviour, Best practices in engineering, Case studies

\hfill *Total: 30*

** Course Outcomes
After the completion of this course, students will be able to: 
- Understand human values (K2).
- Appreciate ethical practices in engineering (K2).
- Adapt ethical practices in engineering and technology (K3).
- Understand organizational environment and culture (K2).
- Apply best practices in engineering (K3).

** References
1. Charles E Harris, Michael S. Protchard and Michael J Rabins,
   ``Engineering Ethics -- Concepts and Cases'', Wadsworth Thompson
   Leatning, United States, 2000 (Indian Reprint now available)
2. Edmund G Seebauer and Robert L Barry, ``Fundamentals of Ethics for
   Scientists and Engineers'', Oxford University Press, Oxford, 2001.
3. Charles D. Fleddermann, ``Engineering Ethics'', Pearson Education /
   Prentice Hall, New Jersey, 2004 (Indian Reprint now available).
4. John R Boatright, ``Ethics and the Conduct of Business'', Pearson
   Education, New Delhi, 2003.
